// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeqsAebeSjpgPUg-1QxUUD54yA99fMcfo',
    appId: '1:418300017547:web:1f67c1bd08e3e5df47cd8e',
    messagingSenderId: '418300017547',
    projectId: 'expenses-c41c5',
    authDomain: 'expenses-c41c5.firebaseapp.com',
    databaseURL: 'https://expenses-c41c5-default-rtdb.firebaseio.com',
    storageBucket: 'expenses-c41c5.firebasestorage.app',
    measurementId: 'G-BS6KRS6RQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0txrpyxywVEG3KnaR2nHWXqZqFpxm13A',
    appId: '1:418300017547:android:d937ec6d777b8a1447cd8e',
    messagingSenderId: '418300017547',
    projectId: 'expenses-c41c5',
    databaseURL: 'https://expenses-c41c5-default-rtdb.firebaseio.com',
    storageBucket: 'expenses-c41c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyhEvJzxns4BJrXuVZbwhPuLixjdYs9jw',
    appId: '1:418300017547:ios:2b78cbdd2a127f6547cd8e',
    messagingSenderId: '418300017547',
    projectId: 'expenses-c41c5',
    databaseURL: 'https://expenses-c41c5-default-rtdb.firebaseio.com',
    storageBucket: 'expenses-c41c5.firebasestorage.app',
    androidClientId: '418300017547-v2rj64h27jbjb8nuvr7rnbq7pmoet3it.apps.googleusercontent.com',
    iosClientId: '418300017547-g30gp8ugbcdd2q911m967un6j47343ol.apps.googleusercontent.com',
    iosBundleId: 'com.example.aexpences',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyhEvJzxns4BJrXuVZbwhPuLixjdYs9jw',
    appId: '1:418300017547:ios:2b78cbdd2a127f6547cd8e',
    messagingSenderId: '418300017547',
    projectId: 'expenses-c41c5',
    databaseURL: 'https://expenses-c41c5-default-rtdb.firebaseio.com',
    storageBucket: 'expenses-c41c5.firebasestorage.app',
    androidClientId: '418300017547-v2rj64h27jbjb8nuvr7rnbq7pmoet3it.apps.googleusercontent.com',
    iosClientId: '418300017547-g30gp8ugbcdd2q911m967un6j47343ol.apps.googleusercontent.com',
    iosBundleId: 'com.example.aexpences',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeqsAebeSjpgPUg-1QxUUD54yA99fMcfo',
    appId: '1:418300017547:web:1f67c1bd08e3e5df47cd8e',
    messagingSenderId: '418300017547',
    projectId: 'expenses-c41c5',
    authDomain: 'expenses-c41c5.firebaseapp.com',
    databaseURL: 'https://expenses-c41c5-default-rtdb.firebaseio.com',
    storageBucket: 'expenses-c41c5.firebasestorage.app',
    measurementId: 'G-BS6KRS6RQ5',
  );

}